###get all users
GET http://localhost:3000/api/user/all

###Register User
POST http://localhost:3000/api/user/register HTTP/1.1
Content-Type: application/json

{
    "email": "testuser3@gmail.com",
    "password": "he0"
}

###Login User
POST http://localhost:3000/api/user/login HTTP/1.1
Content-Type: application/json

{
    "email": "hemkamli425@gmail.com",
    "password": "hem@2810"
}

###get all blogs
GET http://localhost:3000/api/blog/all

###add a new blog
POST http://localhost:3000/api/blog/new HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImVtYWlsIjoiaGVta2FtbGk0MjVAZ21haWwuY29tIn0sImlhdCI6MTcwMzI3ODg5N30.EKMbx7nw6rGPQAQw9fnHZMDcl_mt1Dp4bJ8JYaA_co4

{
    "title": "RE",
    "description": "NodeJs is very helpful in building REST APIs!"
}

###update a blog post 
PUT http://localhost:3000/api/blog/update/6585fddf5a65ba4f6f133ab8 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImVtYWlsIjoiaGVta2FtbGk0MjVAZ21haWwuY29tIn0sImlhdCI6MTcwMzI4MDA3OH0.Y2_Q1Ssu_AkUT3S3nBuGJsUTHRvzntoulg7L7jyHaxI

{
    "description": "Updated NodeJs is very helpful in building REST APIs!"
}

###delete a blog post 
DELETE http://localhost:3000/api/blog/delete/6585faf3c7dd584bce143cfe HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImVtYWlsIjoiaGVta2FtbGk0MjVAZ21haWwuY29tIn0sImlhdCI6MTcwMzI4MDA3OH0.Y2_Q1Ssu_AkUT3S3nBuGJsUTHRvzntoulg7L7jyHaxI

###Search a blog post by title
GET http://localhost:3000/api/blog/search?blogTitle=REST+API

###get a blog post by id
GET http://localhost:3000/api/blog/individual/6585fafc7dd584bce143cfe

